image: maven:3.5.0-jdk-8

pipelines:
  default:
    - step:
        script:
          - git submodule update --init --recursive
          - apt-get update
          - apt-get install -y openjfx
          # - mvn clean install
          - mvn -B verify # -B batch mode makes Maven less verbose